# -*- coding: utf-8 -*-
"""model-detect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UU91D3MTC9Dj6kPxcXwmvWZYhQMWSnb5
"""

!pip -q install transformers datasets underthesea openpyxl accelerate scikit-learn

import pandas as pd
import torch
import re
from datasets import Dataset
from transformers import AutoTokenizer, TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from underthesea import word_tokenize
from google.colab import files

uploaded = files.upload()

train_df = pd.read_excel("train.xlsx")
val_df = pd.read_excel("val.xlsx")
test_df = pd.read_excel("test.xlsx")

train_df = train_df.rename(columns={"content":"text"})
val_df = val_df.rename(columns={"content":"text"})
test_df = test_df.rename(columns={"content":"text"})

vietnamese_stopwords = set([
    "là","và","của","thì","những","các","tại","bị","bởi","với",
    "để","như","này","đó","kia","trong","trên","dưới","cho",
    "về","khi","có","không","gì","nào","đâu","rồi","lại"
])

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^\w\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    words = [w for w in text.split() if w not in vietnamese_stopwords]
    return " ".join(words)

def vietnamese_tokenize(text):
    return word_tokenize(text, format="text")

def preprocess(df):
    df["text"] = df["text"].apply(clean_text)
    df["text"] = df["text"].apply(vietnamese_tokenize)
    return df

train_df = preprocess(train_df)
val_df = preprocess(val_df)
test_df = preprocess(test_df)

train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)
test_dataset = Dataset.from_pandas(test_df)

tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

def tokenize_function(example):
    return tokenizer(
        example["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

train_dataset.set_format(type="torch", columns=["input_ids","attention_mask","label","target_binary"])
val_dataset.set_format(type="torch", columns=["input_ids","attention_mask","label","target_binary"])
test_dataset.set_format(type="torch", columns=["input_ids","attention_mask","label","target_binary"])

import torch.nn as nn
from transformers import AutoModel

class PhoBERT_MTL(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = AutoModel.from_pretrained("vinai/phobert-base")

        hidden_size = self.encoder.config.hidden_size

        # Head 1: 3-class
        self.classifier_label = nn.Linear(hidden_size, 3)

        # Head 2: binary target
        self.classifier_target = nn.Linear(hidden_size, 2)

    def forward(self, input_ids, attention_mask, label=None, target_binary=None):
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = outputs.last_hidden_state[:, 0]

        logits_label = self.classifier_label(pooled_output)
        logits_target = self.classifier_target(pooled_output)

        loss = None
        if label is not None and target_binary is not None:
            loss_fct = nn.CrossEntropyLoss()
            loss1 = loss_fct(logits_label, label)
            loss2 = loss_fct(logits_target, target_binary)
            loss = loss1 + loss2

        return {
            "loss": loss,
            "logits_label": logits_label,
            "logits_target": logits_target
        }

model = PhoBERT_MTL()

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    logits_label, logits_target = logits
    label_true, target_true = labels

    label_pred = logits_label.argmax(axis=1)
    target_pred = logits_target.argmax(axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(label_true, label_pred, average="weighted")
    acc = accuracy_score(label_true, label_pred)

    return {
        "accuracy": acc,
        "f1": f1
    }

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs",
    remove_unused_columns=False
)

class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs["label"]
        targets = inputs["target_binary"]

        outputs = model(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            label=labels,
            target_binary=targets
        )

        loss = outputs["loss"]
        return (loss, outputs) if return_outputs else loss

trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

trainer.train()

def predict_text(text):
    text = clean_text(text)
    text = vietnamese_tokenize(text)

    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=128)
    inputs = {k: v.to(next(model.parameters()).device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

        label_pred = torch.argmax(outputs["logits_label"], dim=-1).item()
        target_pred = torch.argmax(outputs["logits_target"], dim=-1).item()

    # ACTION RULE
    if label_pred == 0:
        action = "ALLOW"
    elif label_pred == 1 and target_pred == 0:
        action = "WARN"
    elif label_pred == 1 and target_pred == 1:
        action = "BLOCK"
    elif label_pred == 2:
        action = "AUTO_BLOCK"

    return label_pred, target_pred, action

samples = [
    "Shop giao hàng nhanh quá",
    "dm cái mạng này",
    "mày ngu quá",
    "bọn miền bắc đúng là rác rưởi"
]

for s in samples:
    print(s, "->", predict_text(s))