# -*- coding: utf-8 -*-
"""Train-model-detect-badwords-12/03-v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZly_fGXmXjbK8XEYX4CQKo7tfKVyarb
"""

!pip install transformers datasets underthesea openpyxl

import pandas as pd
import torch
import re
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from underthesea import word_tokenize

from google.colab import files
uploaded = files.upload()

# LOAD DATA
train_df = pd.read_excel("train.xlsx")
val_df = pd.read_excel("val.xlsx")
test_df = pd.read_excel("test.xlsx")

train_df = train_df.rename(columns={"cmt_col":"text","labels":"label"})
val_df = val_df.rename(columns={"cmt_col":"text","labels":"label"})
test_df = test_df.rename(columns={"cmt_col":"text","labels":"label"})

# STOPWORDS
vietnamese_stopwords = set([
    "là","và","của","thì","những","các","tại","bị","bởi","với",
    "để","như","này","đó","kia","trong","trên","dưới","cho",
    "về","khi","có","không","gì","nào","đâu","rồi","lại"
])

# CLEAN TEXT
def clean_text(text):
    text = str(text).lower()

    # Xóa URL
    text = re.sub(r'http\S+', '', text)

    # Xóa ký tự đặc biệt
    text = re.sub(r'[^\w\s]', ' ', text)

    # Xóa khoảng trắng thừa
    text = re.sub(r'\s+', ' ', text).strip()

    # Xóa stopwords
    words = text.split()
    words = [w for w in words if w not in vietnamese_stopwords]

    return " ".join(words)

# TOKENIZE TIẾNG VIỆT
def vietnamese_tokenize(text):
    if not text:
        return ""
    return word_tokenize(text, format="text")

# ÁP DỤNG TIỀN XỬ LÝ
def preprocess(df):
    df["text"] = df["text"].apply(clean_text)
    df["text"] = df["text"].apply(vietnamese_tokenize)
    return df

train_df = train_df.rename(columns={"content":"text"})
val_df = val_df.rename(columns={"content":"text"})
test_df = test_df.rename(columns={"content":"text"})
train_df = preprocess(train_df)
val_df = preprocess(val_df)
test_df = preprocess(test_df)

# CHUYỂN SANG DATASET HF
train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)
test_dataset = Dataset.from_pandas(test_df)

# TOKENIZER PHOBERT
tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base")

def tokenize_function(example):
    return tokenizer(
        example["text"],   # đúng cột text
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

# FORMAT TORCH
train_dataset.set_format(type="torch", columns=["input_ids","attention_mask","label"])
val_dataset.set_format(type="torch", columns=["input_ids","attention_mask","label"])
test_dataset.set_format(type="torch", columns=["input_ids","attention_mask","label"])

# MODEL PHOBERT
model = AutoModelForSequenceClassification.from_pretrained(
    "vinai/phobert-base",
    num_labels=3
)

# METRICS
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)

    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average="weighted")
    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }

# TRAINING ARGUMENTS
training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    eval_strategy="epoch", # Changed from evaluation_strategy
    save_strategy="epoch",
    logging_dir="./logs"
)

# TRAINER
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

# TRAIN
trainer.train()

# TEST
trainer.evaluate(test_dataset)

import pandas as pd

# Combine labels from all datasets
all_labels = pd.concat([train_df['label'], val_df['label'], test_df['label']])

# Calculate label distribution
label_distribution = all_labels.value_counts().sort_index()

# Define label mapping
label_mapping = {
    0: "Clean",
    1: "Offensive",
    2: "Hate/harassment"
}

# Map numerical labels to descriptive names
mapped_distribution = label_distribution.rename(index=label_mapping)

print("Distribution of labels in the overall dataset:")
print(mapped_distribution)

# Optional: Display percentage distribution
print("\nPercentage Distribution:")
print(mapped_distribution / mapped_distribution.sum() * 100)

